<?php

namespace Drupal\migrate_infob\Plugin\migrate\source;

use Drupal\migrate\Row;
use Drupal\migrate_drupal\Plugin\migrate\source\DrupalSqlBase;

/**
 * Taxonomy term source from database.
 *
 *
 * @MigrateSource(
 *   id = "taxonomy_term_customers",
 *   source_provider = "taxonomy"
 * )
 */
class TermCustomers extends DrupalSqlBase {

  protected $vocabularyName = 'Customers';

  protected $vocVid;

  protected $termsToMigrate = [
    "A Hundred Answers",
    "ABC Financial",
    "ABSA",
    "Absolut",
    "AC Restaurants and Hotels",
    "Ace Hardware Corporation",
    "Acusport",
    "Adif",
    "Advanced Data Exchange",
    "Affinity Plus Federal Credit Union",
    "Agility Logistics",
    "AIG Domestic Claims",
    "Air Canada",
    "Airbus France",
    "AJ Logistics",
    "AkzoNobel",
    "Alberta Culture and Community Spirit",
    "Alcan Aluminum (Novelis)",
    "Allegis Group",
    "Alliance",
    "Alliant",
    "Allianz Leben",
    "Allied Logistics",
    "Alpha Bank",
    "American Identity",
    "American Science & Engineering  (AS&E)",
    "Americo",
    "Amerisure Mutual Insurance Company",
    "Ameritas Acacia Companies",
    "Ameritas Life Insurance Corporation",
    "Anglo Platinum",
    "ANZ Bank",
    "Appvion Inc.",
    "Aqua Clara",
    "Arcadia Group Ltd.",
    "Arinc",
    "ArvinMeritor",
    "ASPCA",
    "Associated Food Stores",
    "Austin University",
    "AutoZone",
    "Aventis Pasteur",
    "Aviall",
    "AVIS RENT A CAR",
    "Bank of Tokyo Mitsubishi Info",
    "Bank Sarasin Benelux (Formerly Rabo Robeco Bank)",
    "Basler Versicherungen",
    "Bayer Consumer Care",
    "BBVA",
    "BC Housing",
    "BC Ministry of Transportation",
    "be2",
    "Be2",
    "BECU (Boeing Employees' Credit Union)",
    "Belcan",
    "Bell Canada",
    "BenchMark Consulting",
    "BGL Group",
    "Black Knight Financial Services",
    "Blue Coat Systems Inc",
    "Blyk",
    "BMO Bank of Montreal",
    "Boeing",
    "Bon Secours Health Systems",
    "Bosch Thermotechnik GmbH",
    "Boston Globe",
    "Bourne Leisure Group",
    "Brinker International",
    "Brotherhood Mutual",
    "Brown University",
    "BT",
    "BT Radianz",
    "Buckman Laboratories",
    "Buhler",
    "Bulova",
    "Bunn-O-Matic Corporation",
    "Bunzl Australasia",
    "Business Connexion",
    "Butler Health System",
    "C.H. Robinson",
    "CAE",
    "California Dept of Social Services",
    "California State Polytechnic University San Luis Obispo",
    "Cambridge Memorial Hospital (CMH)",
    "Canada Pension Plan Investment Board",
    "Canadian Depository for Securities",
    "Canadian Ministry of Alberta Seniors and Community Supports",
    "Canadian National Railway",
    "Canisius Wilhemina Hospital",
    "CANTV",
    "Carlson Hospitality Worldwide",
    "Cars.com",
    "Cascades",
    "CDS Global",
    "CenterStone Technologies",
    "Centimark Corp.",
    "Central Steel and Wire",
    "Century Business Services - CBIZ",
    "CH Mack",
    "Charlotte-Mecklenburg Police Dept",
    "Charter Communications",
    "Chicago Metropolitan Agency for Planning (CMAP)",
    "Children's Memorial Hospital",
    "Chowtaw Nation of Oklahoma",
    "Chu De Besancon",
    "Cigna",
    "Citigroup",
    "Citizens Bank",
    "Citizens Financial Group",
    "City of Chicago",
    "City of Cincinnati",
    "City of Erlanger, Kentucky Police Department",
    "City of Houston Fire Department",
    "City of Houston Planning & Development",
    "City of Houston Police",
    "City of Irving",
    "City of Montreal",
    "City of New York Department of Health",
    "City of Omaha Public Schools",
    "City of Philadelphia Office of Mental Health/Mental Retardation",
    "City of Richardson",
    "City of Richmond (Virginia)",
    "City of Richmond Police Department",
    "City of Richmond, British Columbia",
    "City of Rotterdam",
    "City of Seattle Police Dept",
    "Clarian Health",
    "Clarica",
    "Cleco",
    "CMA Consulting",
    "Co-Operative Bank",
    "Cognos",
    "Collections Etc.",
    "Columbia University",
    "Columbus City Schools (CCS)",
    "Comfort Systems",
    "Commit",
    "Corus",
    "Coty Inc.",
    "Council of Europe",
    "County of Los Angeles",
    "County OF Maricopa",
    "Covanta Energy",
    "Covidien",
    "Covidien UK",
    "Credit Agricole",
    "Credit Mutuel",
    "Cutting Edge Commece",
    "CVS Caremark",
    "D.O.C. Optics Corporation",
    "DA Townley & Associates Inc",
    "Dataspace",
    "Datran Media",
    "Davenport University",
    "De Montfort University (DMU)",
    "Dealer Services",
    "DealerTrack",
    "Delaware County Community College",
    "Der Europarat",
    "Deutsche Telekom (T-Com Division)",
    "Diakonessenhuis",
    "Dialysis Clinic, Inc (DCI)",
    "Dillard's",
    "Diodes",
    "Disc Brakes (Australia)",
    "DKV Seguros",
    "Dollar General",
    "Donatos Pizzeria Corporation",
    "DuPont Information Technology",
    "E*TRADE Financial",
    "E. van Wijk Logistics B.V.",
    "Eastern Mountain Sports",
    "Easynet Global Services",
    "ebrary",
    "Edison Mission Group",
    "Edward Don",
    "Elan Polo",
    "Elie Tahari Ltd.",
    "EllisDon (Edgebuilder)",
    "Emory University",
    "ENBRIDGE",
    "ENSR Consulting and Engineering",
    "ENSR-AECOm",
    "Entertainment Publications",
    "Envision",
    "Equitable Resources, Inc.",
    "Estonia Police Department",
    "Everest Insurance",
    "eWinery Solutions",
    "Executive Intelligence",
    "Exxon Mobil",
    "Fannie Mae",
    "FBI (CJIS)",
    "FDIC",
    "Federal Emergency Management Agency (FEMA)",
    "Federal Express",
    "Federal Home Loan Bank of Boston",
    "Ferris State University",
    "Fidelity",
    "Financial Management Services",
    "First Financial Planners",
    "First Hawaiian Leasing Inc",
    "First Rate Investment Systems",
    "Florida Atlantic University",
    "Florida Atlantic University",
    "Florida Department of Transportation (FDOT)",
    "Florida International University (FIU)",
    "Folksamerica Reinsurance Company",
    "Food For The Poor",
    "Food Lion",
    "Ford Motor Company",
    "Fordham University",
    "Fractal Analytics",
    "Franklin University",
    "Fred's Inc",
    "Freightliner",
    "Friedkin Companies",
    "Friends University",
    "Fujisawa Yakuhin",
    "FulCircle",
    "Gemeente Tilburg Sector Sociale Zaken",
    "Genex Services",
    "Georgia Department of Labor",
    "Gillette",
    "GlaxoSmithKline Consumer Healthcare",
    "Global Payments",
    "GLOBALCOM",
    "GMAC Commercial Finance plc",
    "GoldenSource",
    "Goodfellow",
    "Gordmans",
    "GRAFTECH INTERNATIONAL LTD",
    "Grand River Hospital",
    "Great Lakes Higher Education",
    "Groupe Dynamite",
    "Guardian Group of Funds (GGOF)",
    "Guelph General Hospital",
    "Haggen",
    "Harleysville",
    "Harris Corporation",
    "Harvard Managment Company (HMC)",
    "Harvard Pilgrom Healthcare",
    "Haskell",
    "Haulotte",
    "Heartland Financial",
    "Helzberg Diamond Inc.",
    "Henny Penny Corporation",
    "Henry Ford Community College",
    "Hercules Tire & Rubber Co.",
    "Hertz",
    "Hesse-Noord Natie",
    "Hexion",
    "Highland Community College",
    "Hillerich & Bradsby",
    "Hillman Group",
    "Hofstra University",
    "Holland America",
    "Hospital Diakonessenhuis",
    "Houston Community College System",
    "Houston Police Department",
    "Hunt Petroleum",
    "Hydro One",
    "Hydro-Quebec",
    "IBM (Global Services)",
    "ICL",
    "ICSolutions",
    "Iiuzka Hospital",
    "Indaver",
    "Independent Pharmacy Corp",
    "Industry Canada",
    "Indy Productions",
    "INEOS Oxide",
    "ING",
    "Ingram Books",
    "Insperity",
    "Integral (Cleveland Clinc)",
    "Intermec",
    "International Car Operators",
    "International Factors Belgium",
    "International Financial Data Services (IFDS)",
    "Intersil",
    "iovation",
    "Israeli Credit Insurance Company",
    "J&J Industries",
    "J. Ray McDermott",
    "Jack Nadel",
    "Jaguar - Land Rover",
    "JC Penny",
    "Jefferson Regional Medical Center",
    "Jo-Ann Stores Incorporated",
    "Jobs2Web",
    "Johns Hopkins University",
    "JP Morgan Chase",
    "Julius Zorn, Ltd.",
    "Junkers",
    "Kaiser Permanente",
    "Kalamazoo Valley Community College (KVCC)",
    "Kehe Food Distributors",
    "Kempen & Co",
    "Ketering Medical Center Network",
    "KKA Japan",
    "KLM (Royal Dutche Airlines)",
    "KnowledgeBase Marketing (KBM)",
    "Koch Industries",
    "Koch Mineral Services",
    "Kronos",
    "La Caixa - Caixa d´estalvis i Pensions de Barcelona",
    "La Petite Academy Inc",
    "LaBarge, Inc.",
    "Lafarge Aso Cement Co., Ltd.",
    "Larson Juhl",
    "Lawson Products Inc.",
    "LB Foster",
    "LeanLogistics",
    "Leapfrog Online",
    "Lehigh Valley Health Network (LVHN)",
    "Lender Processing Services",
    "Levy",
    "Lloyds Corporation of London",
    "LMS",
    "Lockheed Martin Missiles and Fire Control",
    "London NHS Foundation Trust",
    "Lowell General Hospital",
    "Lutheran Life Communities",
    "Maasstad Hospital",
    "Macy's",
    "Management Company (SMC)",
    "MapR",
    "Marathon Oil",
    "Mark Anthony Group",
    "Marquette University",
    "Marvin F Poer. LLC (MFP)",
    "Massachusetts School System",
    "Maverick Transportation",
    "MCRZ (Masstad Ziekenhuis)",
    "Medical Associates Health Centers",
    "Medish Centrum Rijmund Zuid",
    "Medline Industries, Inc.",
    "MedStar",
    "Megamation Systems",
    "Meherry Medical College",
    "Memorial Healthcare Systems",
    "Mercurial Insights",
    "Mid-Continent Casualty Company",
    "Milton Hershey School",
    "Ministerio De Trabajo E Inmigracion",
    "Ministry of Alberta Seniors and Community Supports",
    "Minnesota Department of Education",
    "Missouri Institute of Mental Health",
    "Mobile Mini",
    "Moneris Solutions",
    "Mortgage Guarantee Insurance Corp.",
    "Mount Sinai Hospital",
    "Mount Sinai NYU Health",
    "Multiple Customers Mentioned",
    "Municipality of Tilburg",
    "Murphy Hoffman Company",
    "NASA",
    "National Association of Insurance Commissioners (NAIC)",
    "National Futures Association, Inc.",
    "National Vision Administration",
    "Nationwide",
    "Naval Surface Warfare Center, Indian Head Division",
    "NBTY",
    "Neiman Foods",
    "Neiman Marcus",
    "Netherlands Home Office",
    "New York City Department of Justice",
    "New York City PHIN",
    "New York City Police Department",
    "New York Public Library",
    "New York State Insurance Fund",
    "NHL Foundation Trust",
    "North American Lighting",
    "North Carolina Farm Bureau",
    "North Harris Montgomery Community College District",
    "North Texas Health & Science Center",
    "North Texas Health and Science Center",
    "NorthBound Solutions, Inc. (NBS)",
    "Northrop Grumman",
    "Novelis (Alcan)",
    "NYC Board of Education",
    "NYU Medical Center",
    "Oakville",
    "OAR",
    "OFS Brands",
    "OIA Global Logistics",
    "OmniCare",
    "OnApproach",
    "Ontario Provincial Government",
    "Orange & Rockland Utilities",
    "Orange County Florida",
    "Oxford Properties Group",
    "Ozburn-Hessey Logistics",
    "P&O Ports",
    "PACCAR",
    "Pacific Blue Cross",
    "Pacific Cycle",
    "Page Plus Cellular",
    "Pamida",
    "Parker Hannifin",
    "Passalong Networks",
    "Paycor",
    "Paypal",
    "PeaceHealth",
    "Pennsylvania Public Utilities Commission (PUC)",
    "Perceptive Informatics",
    "Pernod Ricard Nordic",
    "Pershing",
    "Petro-Canada",
    "Petrobras",
    "PGWC Education South Africa",
    "Pharmascience",
    "Philadelphia Office of Mental Health",
    "Philips Consumer Electronics (CE)",
    "Physicians Mutual Insurance",
    "Pichler Computing",
    "Pierre Foods, Inc.",
    "Pilkington",
    "Plexus Medical Group",
    "Plus Relocation Services",
    "PNC Bank National Financial Services Center",
    "Poudre Valley",
    "Power & Telephone Supply Co., Inc.",
    "Power Systems Research",
    "Premier Manufacturing",
    "Preso Omni Care",
    "PricewaterhouseCoopers Business Process Outsourcing Solutions Inc.",
    "Principal Financial Group",
    "PRISM Group",
    "ProRail",
    "Provincial Health Services Authority",
    "PSA Peugeot",
    "Qenos",
    "Qwest",
    "Rabobank",
    "RainTree Oncology Services",
    "Randstad Biljique",
    "RBC Financial",
    "RBC Royal Bank of Canada",
    "RealD",
    "Renfe",
    "Retail Decision",
    "Rexel",
    "REZ-1 Transportation",
    "Richmond British Columbia",
    "Ricoh Leasing",
    "RIVM State Institute of Public Heatlh",
    "Roche",
    "Roll Coater",
    "RosettaNet",
    "Royal Bank of Canada",
    "Royal State Financial Corporation {DTRIC}",
    "RWE AG",
    "S. Abraham & Sons",
    "Sabre Holding Corporation",
    "Safilo Group",
    "Saint Gobain Weber",
    "Saint Louis University",
    "Saks Fifth Avenue",
    "Samsonite",
    "San Francisco Chronicle",
    "San Jacinto College",
    "Sanmina SCI Corporation",
    "Saudi Arabian National Guard Health Affairs",
    "Saudi Company for Hardware (SACO)",
    "Schawk",
    "Schenker of  Canada Ltd.",
    "Scherer Brothers Lumber Co.",
    "Schnuck Market",
    "Scotiabank",
    "Scottish and Southern Energy",
    "SDV International Logistics",
    "Seaton",
    "SEB Private Bank",
    "Seco",
    "Secretaría de Seguridad Pública",
    "Securex",
    "Security Check",
    "Seimens",
    "Select Medical",
    "Select Medical Short",
    "Senior Health Insurance Company of PA (SHIP)",
    "Severstal",
    "Shanghai Railway Central Hospital",
    "Sharp Microelectronics",
    "Shikoku Electric Power Co., Inc.",
    "Shink Wang Life Insurance",
    "Siksika Nation",
    "Siplec",
    "SMACL",
    "SMBC Finance Service Co., Ltd.",
    "SNCF",
    "SocialSecurity Administration (SSA)",
    "Sony",
    "South Carolina Student Loan",
    "Southwest Business Corporation (SWBC)",
    "Spanish Confederation of Savings Banks (CECA)",
    "Sparta Systems",
    "Spicer Gelenkwellenbau",
    "Stanford Management Company",
    "Star Lumber",
    "Starwood Hotel and Resorts Worldwide, Inc.",
    "State of California Department of Health Services (DHS)",
    "State of Colorado Department of Corrections",
    "State of Delaware - Department of Health and Social Services",
    "State of Delaware - Department of Justice",
    "State of Florida Department of Financial Services",
    "State of Houston Police Department",
    "State of Indiana PERF Selects",
    "State of Iowa (Justice System)",
    "State of Kentucky",
    "State of Kentucky (Northern Kentucky Area Planning Commission)",
    "State of Louisiana  Department of Social Services",
    "State of Maryland (County of Prince George)",
    "State of Maryland Department of Health and Mental Hygiene",
    "State of Michigan",
    "State of Michigan Department of Justice (County of Wayne)",
    "State of Mississippi Department of Human Services",
    "State of Missouri",
    "State of Missouri Department of Social Services",
    "State of New Hampshire Dept. of Revenue Admin.",
    "State of New Mexico",
    "State of Oklahoma",
    "State of Oklahoma Department of Human Services (OKDHS)",
    "State of Pennsylvania State Police",
    "State of Utah",
    "Statistical Institute of Jamacia (STATIN)",
    "Stephen F. Austin State University (SFA)",
    "Strata Decision Technology",
    "Strategic Fulfillment Group",
    "Sunoco",
    "Swifttrade",
    "SwiftTrade",
    "Sybron Dental Specialties",
    "t.a.c",
    "TAC, LLC",
    "Target",
    "Tarleton State University",
    "Telephone Electronics Corporation",
    "Telus",
    "Tennessee Farm Bureau Federation",
    "Tesch Global",
    "Tesco",
    "Texas Instruments",
    "The Dutch Cancer Institute-Antoni van Leeuwenhoek Hospital (NKI-AVL)",
    "The Gap",
    "The Paradies Shops",
    "Thomas Publishing Company",
    "ThyssenKrupp AG",
    "Time Inc",
    "Topco Associates LLC",
    "Toppan InterAmerica",
    "Toshiba Personal Computer System",
    "Tower Federal Credit Union",
    "Tozzo AG",
    "Travel and Transport, Inc.",
    "TriHealth",
    "Trizetto Group",
    "Trustmark Insurance Company",
    "TTX",
    "TUI UK",
    "Tyson Foods",
    "U.S. Air and Space Expeditionary Force",
    "U.S. Air Force Air Mobility Command",
    "U.S. Army / ASM Research",
    "U.S. Army Corp of Engineers",
    "U.S. Army Global Command and Control System",
    "U.S. Bancorp",
    "U.S. Bank",
    "U.S. Department of Defense",
    "U.S. Department of Education",
    "U.S. Department of Justice",
    "U.S. Department of Transportation",
    "U.S. EPA",
    "U.S. Navy/CTSC",
    "U.S. Postal Service",
    "U.S. Transportation Command",
    "UBM Global Trade",
    "Union Pacific Railroad",
    "United Automobile Insurance Company",
    "United Financial of Japan",
    "United Nations",
    "United States Department of Education",
    "United Stationers Supply Company",
    "Universal Air Travel Plan",
    "University Hospital of Besan&ccedil;on",
    "University of CT Health Center",
    "University of Flint Michigan",
    "University of Massachusetts",
    "University of Nebraska and Nebraska State College System",
    "University of Nebraska Omaha",
    "University of North Carolina Charlotte",
    "University of North Texas Health Science Center",
    "University of the Fraser Valley",
    "University of Virginia",
    "Upstream Professionals",
    "US Army G2",
    "USDA",
    "Utah Valley University",
    "Utz Quality Foods, Inc.",
    "Vacation.com",
    "Valero Energy Corp.",
    "Velsicol Chemical Corporation",
    "Verizon",
    "Victory Packaging",
    "Vin & Spirit Group",
    "Virginia Commonwealth University",
    "VP Buildings",
    "Vree Health",
    "Vulcan Materials Co",
    "Walmart",
    "Walsworth Publishing",
    "Washington Hospital Center",
    "Weitz Company",
    "Wendy's",
    "Wesco International",
    "Western Power Distribution",
    "Wheels Inc",
    "Wilmington Trust Corporation",
    "WonenCentraal",
    "Workers Compensation Fund",
    "World Wide Supply",
    "World Wide Technology, Inc.",
    "Xircom",
    "Yellow Pages",
    "Yellowpages.com LLC",
    "Yeshiva University",
    "Zurich Financial Services (Australia)"
  ];

  /**
   * {@inheritdoc}
   */
  public function query() {
    if (empty($this->topicsVid)) {
      $vid = $this->select('vocabulary', 'v')
                  ->fields('v', ['vid'])
                  ->condition('name', $this->vocabularyName)
                  ->distinct()
                  ->execute()
                  ->fetchCol();
      $this->vocVid = $vid;
    }
    $query = $this->select('term_data', 'td')
                  ->fields('td')
                  ->distinct()
                  ->orderBy('td.tid');

    if (isset($this->vocVid)) {
      $query->condition('td.vid', $this->vocVid);
    }
    $query->condition('name', $this->termsToMigrate, 'IN');

    return $query;
  }

  /**
   * {@inheritdoc}
   */
  public function fields() {
    $fields = [
      'tid' => $this->t('The term ID.'),
      'vid' => $this->t('Existing term VID'),
      'name' => $this->t('The name of the term.'),
      'description' => $this->t('The term description.'),
      'weight' => $this->t('Weight'),
    ];

    return $fields;
  }

  /**
   * {@inheritdoc}
   */
  public function prepareRow(Row $row) {
    return parent::prepareRow($row);
  }

  /**
   * {@inheritdoc}
   */
  public function getIds() {
    $ids['tid']['type'] = 'integer';
    return $ids;
  }

}
